version: "3.8"
services:

  filebeat01:
    container_name: filebeat
    network_mode: soc_net
    image: docker.elastic.co/beats/filebeat:7.17.16
    command: [ "--strict.perms=false","setup"] ## 
    user: root
    volumes:
      - filebeatdata01:/usr/share/filebeat/data
      - /var/log/suricata:/var/log/suricata
      - /logs/osqueryd.results.log:/logs/osqueryd.results.log
      - "./filebeat.yml:/usr/share/filebeat/filebeat.yml:ro"
      - "/var/lib/docker/containers:/var/lib/docker/containers:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    environment:
      - ELASTIC_HOSTS=http://elasticsearch:9200
      - ELASTICSEARCH_USERNAME=elastic
      - ELASTICSEARCH_PASSWORD=elastic
      - KIBANA_HOSTS=http://kibana:5601


volumes:
   filebeatdata01:

